#!/bin/sh

cd rom_d && /usr/sbin/smake -n -f ../Makefile  USE_HIRESO= USE_LOCALE= USE_FLASHROM= USE_CIC6105= NES_VERSION= ROM_D= USE_CIC6105_NOCHECK= USE_THREAD_PROFILE= USE_COUNT= DEBUG_CAMERA= USE_DEBUG_MALLOC= VIDEO_AUTO= ISVIEWER=  rom

